package SMPL.syntax;

import SMPL.semantics.Visitor;
import java.util.ArrayList;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTConditional extends ASTExp {
  ASTExp condition;
  ArrayList<ASTExp> body;
  ArrayList<ASTExp> alt;
  
  public ASTConditional(ASTExp condition, ASTExpSequence s) {
    this.condition = condition;
    this.body = s.getSeq();
  }

  public ASTConditional(ASTExp condition, ASTExpSequence s, ASTExpSequence f) {
    this.condition = condition;
    this.body = s.getSeq();
    this.alt = f.getSeq();
  }

  public ASTExp getCondition() {
    return condition;
  }
  
  public ArrayList<ASTExp> getBody() {
      return body;
  }
  
  public ArrayList<ASTExp> getalt() {
      return alt;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTConditional(this, arg);
  }

}
