package SMPL.syntax;

import SMPL.semantics.Visitor;

/**
  Class ASTExpVar.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTComment extends ASTExp {
  String var;

  public ASTComment (String var) {
    this.var = var;
  }

  public String getVar() {
    return var;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTComment(this, arg);
  }

}
