package SMPL.syntax;

import SMPL.semantics.Clause;
import SMPL.semantics.Visitor;
import java.util.ArrayList;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTCase extends ASTExp {
  ArrayList<Clause> body;

  public ASTCase(ArrayList<Clause> s) {
    this.body = s;
  }
  
  public ArrayList<Clause> getBody() {
      return body;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTCase(this, arg);
  }

}
