package SMPL.syntax;

import SMPL.semantics.Visitor;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTDefine extends ASTStatement {
  String var;
  ASTExp valueExp;

  public ASTDefine (String var,ASTExp valueExp) {
    this.var = var;
    this.valueExp = valueExp;
  }

  public String getVar() {
    return var;
  }

  public ASTExp getValueExp() {
    return valueExp;
  }

  @Override
  public Object visit(Visitor v, Object state) throws Exception {
    return v.visitASTDefine(this, state);
  }

}
