package SMPL.syntax;

import SMPL.semantics.Visitor;
import java.util.ArrayList;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTDefine extends ASTStatement {
  ArrayList<String> var;
  ArrayList<ASTExp> valueExp;

  public ASTDefine (String var,ASTExp valueExp) {
    this.var = new ArrayList<>();
    this.valueExp = new ArrayList<>();
    this.var.add(var);
    this.valueExp.add(valueExp);
  }
  
  public ASTDefine (ArrayList<String> var,ArrayList<ASTExp> valueExp) {
    this.var = var;
    this.valueExp = valueExp;
  }

  public ArrayList<String> getVar() {
    return var;
  }

  public ArrayList<ASTExp> getValueExp() {
    return valueExp;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTDefine(this, arg);
  }

}
