package SMPL.syntax;

import SMPL.semantics.Visitor;

/**
  Class ASTExpSub.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTExpNot extends ASTExp {
  ASTExp exp;

  public ASTExpNot (ASTExp exp) {
    this.exp = exp;
  }

  public ASTExp getExp() {
    return exp;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTExpNot(this, arg);
  }

}
