package SMPL.syntax;

import SMPL.semantics.Visitor;

/**
  Class ASTExpVar.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTExpChar extends ASTExp {
  Character var;

  public ASTExpChar (Character var) {
    this.var = var;
  }

  public Character getVar() {
    return var;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTExpChar(this, arg);
  }

}
