package SMPL.syntax;

import SMPL.semantics.Visitor;

/**
 * Class ASTProgram. Intermediate representation class autogenerated by
 * CS34Q semantic generator. Created on Sat Oct 12 03:13:16 2013
 */
public class ASTProgram extends ASTStatement{

    ASTStmtSequence statements;

    public ASTProgram(ASTStmtSequence statements) {
        this.statements = statements;
    }

    /**
     *
     * @return The sequence of statements making up this program
     */
    public ASTStmtSequence getStatements() {
        return statements;
    }

    @Override
    public Object visit(Visitor v, Object state) throws Exception {
        return v.visitASTProgram(this, state);
    }
}
