package SMPL.syntax;

import SMPL.semantics.Visitor;
import java.util.ArrayList;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTProcCall extends ASTStatement {
  String name;
  ASTExp args;

  public ASTProcCall (String name,ASTExp args) {
    this.name = name;
    this.args = args;
  }

  public String getName() {
    return name;
  }
  
  public ASTExp getArgs() {
      return args;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTProcCall(this, arg);
  }

}
