package SMPL.syntax;

import SMPL.semantics.Visitor;
import java.util.ArrayList;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTProcDef extends ASTStatement {
  String rest;
  ArrayList<String> ids;
  ASTStmtSequence body;

  
  public ASTProcDef (ArrayList<String> ids, ASTStmtSequence body) {
    this.ids = ids;
    this.body = body;
  }
  
  public ASTProcDef (String id, ASTStmtSequence body) {
    ids = new ArrayList<String>();
    ids.add(id);
    this.body = body;
  }
  
  public ASTProcDef (ArrayList<String> ids, String rest, ASTStmtSequence body) {
    this.rest = rest;
    this.ids = ids;
    this.body = body;
  }

  public String getRest() {
    return rest;
  }
  
  public ArrayList<String> getIds() {
      return ids;
  }

  public ASTStmtSequence getBody() {
    return body;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTProcDef(this, arg);
  }

}
