package SMPL.syntax;

import SMPL.semantics.Visitor;
import java.util.ArrayList;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTProcCall extends ASTStatement {
  String name;
  ArrayList<ASTExp> ids;

  public ASTProcCall (String name, ArrayList<ASTExp> ids) {
    this.name = name;
    this.ids = ids;
  }

  public String getName() {
    return name;
  }
  
  public ArrayList<ASTExp> getIds() {
      return ids;
  }

  @Override
  public Object visit(Visitor v, Object arg) throws Exception {
    return v.visitASTProcCall(this, arg);
  }

}
