package SMPL.syntax;

import SMPL.semantics.Visitor;

/**
 * Class ASTProgram. Intermediate representation class autogenerated by
 * CS34Q semantic generator. Created on Sat Oct 12 03:13:16 2013
 */
public class ASTProgram extends ASTExp{

    ASTExpSequence statements;

    public ASTProgram(ASTExpSequence statements) {
        this.statements = statements;
    }

    /**
     *
     * @return The sequence of statements making up this program
     */
    public ASTExpSequence getStatements() {
        return statements;
    }

    @Override
    public Object visit(Visitor v, Object arg) throws Exception {
        return v.visitASTProgram(this, arg);
    }
}
