package SMPL.syntax;

import SMPL.semantics.Visitor;
import java.util.ArrayList;

/**
  Class ASTDefine.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTProcDef extends ASTStatement {
  String name;
  ArrayList<String> ids;
  ASTStmtSequence body;

  public ASTProcDef (String name, ArrayList<String> ids, ASTStmtSequence body) {
    this.name = name;
    this.ids = ids;
    this.body = body;
  }

  public String getName() {
    return name;
  }
  
  public ArrayList<String> getIds() {
      return ids;
  }

  public ASTStmtSequence getBody() {
    return body;
  }

  @Override
  public Object visit(Visitor v, Object state) throws Exception {
    return v.visitASTProcDef(this, state);
  }

}
